title: Interaction 2
email: cschmidt@cca.edu
description: "A course about browser exploration at California College of the Arts in the Fall of 2017"
baseurl: "http://doing.computer/interaction-2" # the subpath of your site, e.g. /blog
url: "http://doing.computer/interaction-2" # the base hostname & protocol for your site
github_username: cls-teaching
